# Generated by Django 3.2.16 on 2023-10-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
